#!/bin/sh
#/etc/NetworkManager/dispatcher.d/univpn

#Parameter einlesen
INTERFACE_COMMITTED=$1
ACTION=$2

#Session-ID des Uni-WLANs
ESSID="wlanipsec"

#WLAN-Schnittstelle?
INTERFACE="eth1" # WLAN Interface, kann auch eth1 oder wlan0 sein. Bekommt man mit $iwconfig raus

#Skript verlassen, wenn das übergebene Interface nicht das des WLANs ist
if [ "$INTERFACE" != "$INTERFACE_COMMITTED" ]; then
    exit 0
fi

#existiert eine Verbindung zu einem Netz mit der ESSID?
ESSID_EXISTS=$(iwconfig $INTERFACE|grep $ESSID|awk {'print $4'})

#Skript verlassen, wenn das WLAN das falsche ist
if [ "$ESSID_EXISTS" = "" ]; then
    exit 0
fi

#Funktionen durchführen, je nach Aktion eine andere
case "$ACTION" in
    up)
        #VPNC starten
        vpnc /etc/vpnc/vpncint.conf
	sleep 3
	ifconfig tun0 mtu 1250       
	;;
    down)
        #VPNC stoppen
        killall vpnc
        ;;
    pre-up)
        #ein vorher laufendes VPNC stoppen
        killall vpnc
        ;;
    post-down)
        #VPNC wirklich stoppen, falls abgestürzt
        killall -9 vpnc
        ;;
    *)
        echo "$0: aufgerufen mit falschem Parameter \`$ACTION'" 1>&2
        exit 1
        ;;
esac