#!/bin/zsh
#
# change default behaviors for the basics

. ~/.zsh/vars

alias mv='mv -v --backup=existing'
alias mmv='noglob zmv -W'
alias rm='rm -v'
alias cp='cp -v'
alias firefox='/usr/bin/firefox'
alias mplayer='mplayer -idx'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'

alias pip='python-pip'

#function call
alias ex=extract_archive

# basics
#alias c='clear'
alias l='ls -la'
#alias ll='ls -ahl --color | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
#alias ls='ls -hF -a --color=auto'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='eog'
# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}='mplayer -idx'
# auto open audio
alias -s {mp3,ogg,wav,flac}='cmus'
# auto open web addresses
if [ "$BROWSER" ]; then
    alias -s {html,php,com,net,org,gov}="$BROWSER"
fi
# auto open regular files
alias -s txt='e'
alias -s pdf='evince'

alias ev='evince'
alias wcat='wget -q -O -'
alias reboot='sudo reboot'
alias qtc='qtcreator'

alias mat='matlab -nosplash'
alias cmat='matlab -nodesktop -nosplash -nojvm'

embin="/usr/bin/emacs"
if [ "$EMBINPATH" ]; then
    embin="$EMBINPATH/emacs"
fi

consoleemacs="emacsclient -nw -a $embin"
guiemacs="emacsclient -nc" # -a $embin"
alias E="$guiemacs"
alias e="$consoleemacs"
alias emacs="$embin"

alias ipycomp='(cd ${GITR}/ipython && git pull && ./setup.py build && sudo ./setup.py install)'
alias ipnb='ipython notebook --pylab=inline --notebook-dir ${GITR}/ipython_workspace'
alias imsipnb='ipython notebook --pylab=inline --notebook-dir ${GITR}/ipython_workspace/ims'
alias psipnb='ipython notebook --pylab=inline --notebook-dir ${GITR}/POC-scripts/trunk/doc/examples'

alias svim='sudo /usr/bin/vim'
alias v='vim'

alias pgnup='gnuplot -persist'
alias nautilus='nautilus --no-desktop'

alias removepyc='rm `find . -iname "*.pyc"`'
alias removelog='rm `find . -iname "*.log"`'

#named directories
HOSTNAME=`hostname`
if [ "$HOSTNAME" = "pc-52-rh" ]; then
    alias svnextlist="svn propget svn:externals -R"
    hash -d strunk=/opt/sandboxes/trunk
    hash -d sbranch=/opt/sandboxes/current_branch
    hash -d spoc=/opt/sandboxes/poc4imo
    hash -d pst=${HOME}/gitrepos/POC-scripts/trunk
    hash -d psb=${HOME}/gitrepos/POC-scripts-POC4IMO
    hash -d hwt=~strunk/HWCtrl
    hash -d hwb=~spoc/HWCtrl
    hash -d hwp=~sbranch/HWCtrl
    hash -d tp1=~/gitrepos/tools/poc1
    hash -d tp2=~/gitrepos/tools/poc2
    hash -d pyspu=~/gitrepos/pyspu.git/trunk
fi
if [ "$HOSTNAME" = "cobra" ]; then
    hash -d pst=${HOME}/gitrepos/POC-scripts/trunk
fi

DOTFDIR=${GITR}/dotfiles
hash -d conf=${HOME}/.config
hash -d loc=${HOME}/.local
hash -d awe=${HOME}/.config/awesome
hash -d dotf=${DOTFDIR}
hash -d emd=${DOTFDIR}/emacs.d
hash -d egd=${DOTFDIR}/emacs.d/el-get
hash -d gr=${GITR}
