#!/bin/zsh
#
# change default behaviors for the basics

. ~/.zsh/vars

alias mv='mv -v --backup=existing'
alias mmv='noglob zmv -W'
alias rm='rm -v'
alias cp='cp -v'
alias mplayer='mplayer -idx'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'
alias tmux='tmux -2' # if tmux messes up on 256color terminals

alias start_btsync='btsync --config ~/btsync_config/config.json'

# conda
alias cua='enconda && conda update --all'
alias ci='enconda && conda install'
alias cs='enconda && conda search'
alias cl='enconda && conda list'
alias cinf='enconda && conda info -e'
alias cr='enconda && conda remove --use-index-cache'
alias workon='enconda && source activate'
alias workoff='enconda && source deactivate'

alias rng='ranger'
# alias pip='python-pip'
alias ipy='ipython --no-confirm-exit'
alias bp='bpython-curtsies'
alias pyc='pycharm.sh'
alias py='python'
alias piu='py setup.py install --user'
alias pi='py setup.py install'
alias pd='py setup.py develop'
alias pib='py setup.py build'
alias pie='pip install -e .' # editable install
alias pympi='mpirun -n `nproc` python'
alias upgrade_all_pip_packes='pip freeze --local | grep -v "^\-e" | cut -d = -f 1  | xargs -n1 pip install -U'

# remove py2 stuff and use py3 tools:
# remove the aliases once fedora has switched to python3
#alias pep8='python3-pep8'
#alias flake8='python3-flake8'
#alias pyflakes='python3-pyflakes'
#alias coverage='python3-coverage'
#alias pip='pip' # TODO only use this alias if not in conda environment
# alias upxonsh='pip3.4 install xonsh --user -U'
alias upxonsh='pip3 install git+https://github.com/xonsh/xonsh.git --user -U'

alias dst='docker stop -t 1'

alias -g G='| egrep'

#function call
alias ex=extract_archive

# basics
#alias c='clear'
alias l='ls -la'
alias ll='ls -ahl --color | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
#alias ls='ls -hF -a --color=auto'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='eog'
# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}='mplayer -idx'
# auto open audio
alias -s {mp3,ogg,wav,flac}='cmus'
# auto open web addresses
if [ "$BROWSER" ]; then
    alias -s {html,php,com,net,org,gov}="$BROWSER"
fi
# auto open regular files
alias -s txt='e'
alias -s pdf='okular'

alias wcat='wget -q -O -'
alias reboot='sudo reboot'

alias i='noglob i'

embin="/usr/bin/emacs"
if [ "$EMBINPATH" ]; then
    embin="$EMBINPATH/emacs"
fi

alias svim='sudo /usr/bin/vim'
alias v='vim'

alias pgnup='gnuplot -persist'
alias nautilus='nautilus --no-desktop'
alias kpx='~/gitrepos/keepassx/build/src/keepassx'

function nestedrm() {
    files=$(find . -iname "$1")
    # TODO extra check
    echo $files
    rm -f $files
}

alias removepyc='rm -f `find . -iname "*.pyc"` && rm -rf `find . -iname "__pycache__"`'

#FIXME don't create pyc files as superuser
alias removepycsudo='sudo rm -f `find . -iname "*.pyc"` && sudo rm -rf `find . -iname "__pycache__"`'

alias removelog='rm -f`find . -iname "*.log"`'
#alias removeng='rm -f `find . -iname "ng.ini" \
#                           -o -iname "ng.prof" \
#                           -o -iname "ngmesh.ini" \
#                           -o -iname "ng0.trace"`'
alias removelatex='rm -f `find . -iname "*.log" -o -iname "*.aux" -o -iname "*.out"` && rm -rf `find . -iname auto -type d`'

if [ -e /usr/bin/dnf ]; then
    alias di='sudo dnf install'
    alias dinf='sudo dnf info'
    alias dnu='sudo dnf update'
    alias ds='sudo dnf search'
    alias dr='sudo dnf remove'
    alias drq='sudo dnf repoquery --installed'
else
    alias di='sudo aptitude install'
    alias dnu='sudo aptitude update && sudo aptitude upgrade'
    alias ds='sudo aptitude search'
    alias dr='sudo aptitude remove'
fi

alias ka='sudo killall'

#named directories
DOTFDIR=${GITR}/dotfiles
hash -d conf=${HOME}/.config
hash -d loc=${HOME}/.local
hash -d awe=${HOME}/.config/awesome
hash -d diss=${GITR}/diss
hash -d dotf=${DOTFDIR}
hash -d dotfp=${DOTFDIR}_personal
hash -d emd=${DOTFDIR}/emacs.d
hash -d gr=${GITR}
hash -d sp37=/usr/lib/python3.7/site-packages
hash -d sp6437=/usr/lib64/python3.7/site-packages
