#!/bin/zsh
#
# change default behaviors for the basics

. ~/.zsh/vars

alias mv='mv -v --backup=existing'
alias mmv='noglob zmv -W'
alias rm='rm -v'
alias cp='cp -v'
alias mplayer='mplayer -idx'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'

alias -g G='| egrep'

# alias pip='python-pip'

#python stuff
alias workon='source activate'
alias workoff='source deactivate'

#function call
alias ex=extract_archive

# basics
#alias c='clear'
alias l='ls -la'
alias ll='ls -ahl --color | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
#alias ls='ls -hF -a --color=auto'

# auto open images
alias -s {jpg,JPG,jpeg,JPEG,png,PNG,gif,GIF}='eog'
# auto open movies
alias -s {mpg,mpeg,avi,ogm,wmv,m4v,mp4,mov}='mplayer -idx'
# auto open audio
alias -s {mp3,ogg,wav,flac}='cmus'
# auto open web addresses
if [ "$BROWSER" ]; then
    alias -s {html,php,com,net,org,gov}="$BROWSER"
fi
# auto open regular files
alias -s txt='e'
alias -s pdf='evince'

alias ev='evince'
alias wcat='wget -q -O -'
alias reboot='sudo reboot'
alias qtc='qtcreator'

alias mat='matlab -nosplash'
alias cmat='matlab -nodesktop -nosplash -nojvm'


embin="/usr/bin/emacs"
if [ "$EMBINPATH" ]; then
    embin="$EMBINPATH/emacs"
fi

consoleemacs="emacsclient -nw -a $embin"
guiemacs="emacsclient -nc" # -a $embin"
alias e="$guiemacs"
alias ec="$consoleemacs"
# alias emacs="$embin"
#alias emacs="$guiemacs"

alias in='ipython notebook'
alias env3k='enconda; workon py3k'

alias svim='sudo /usr/bin/vim'
alias v='vim'

alias pgnup='gnuplot -persist'
alias nautilus='nautilus --no-desktop'

alias removepyc='rm -f `find . -iname "*.pyc"`'
alias removelog='rm -f`find . -iname "*.log"`'

alias st='~/Downloads/sublime_text_3/sublime_text'

alias ipy='ipython --no-confirm-exit'
alias bp='bpython-curtsies'
alias pyc='pycharm.sh'
alias py='python'
alias piu='py setup.py install --user'
alias pi='py setup.py install'
alias pib='py setup.py build'

alias di='sudo dnf install'
alias dnu='sudo dnf update'
alias ds='sudo dnf search'
alias dr='sudo dnf remove'

alias cmx='chmod +x'

#named directories
HOSTNAME=`hostname`
if [ "$HOSTNAME" = "dirac" ]; then
    alias vsc='ssh thisch@vsc.tuwien.ac.at -X -A'
    alias vsc2='ssh thisch@vsc2.tuwien.ac.at -X -A'
    alias ng='LD_PRELOAD=~/libpardiso500-GNU481-X86-64.so:/usr/lib64/libm.so:/usr/lib64/liblapack.so:/usr/lib64/libblas.so  netgen'
    hash -d t3=${GITR}/task3
fi
if [ "$HOSTNAME" = "cobra" ]; then
    hash -d t3=${GITR}/diss/task3
    hash -d pys=${GITR}/diss/pysalt
fi

DOTFDIR=${GITR}/dotfiles
hash -d conf=${HOME}/.config
hash -d loc=${HOME}/.local
hash -d awe=${HOME}/.config/awesome
hash -d diss=${GITR}/diss
hash -d dotf=${DOTFDIR}
hash -d emd=${DOTFDIR}/emacs.d
hash -d egd=${DOTFDIR}/emacs.d/el-get
hash -d gr=${GITR}
hash -d sp27=/usr/lib/python2.7/site-packages
hash -d sp6427=/usr/lib64/python2.7/site-packages
